name: Update Secrets Manager Secret

on:
  workflow_dispatch:
    inputs:
      secret_name:
        description: "Name of the AWS Secret"
        required: true
      secret_payload:
        description: "New secret JSON string"
        required: true

jobs:
  update-secret:
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write  # 🔑 Needed to authenticate with AWS OIDC
      contents: read

    steps:
      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::022499021574:role/fh-cicd-update-secret-role
          aws-region: ap-southeast-1

      - name: Update AWS Secret
        run: |
          echo "Updating secret ${{ github.event.inputs.secret_name }}"
          aws secretsmanager update-secret \
            --secret-id "${{ github.event.inputs.secret_name }}" \
            --secret-string '${{ github.event.inputs.secret_payload }}'
